### ISSUE TITLE
Fix Prediction

### ISSUE THREAD

**Issue by Ra1nerZufall** [DuplosFidibuss/academic-time-planner#112]
Prediction uses the start date atm.
this should be looked at again.
GetRemainingDuration() seems to be the issue.

line 132 in planProject

public double GetRemainingDuration()
        {
            return GetDurationInTimeRange(DateTime.Today.AddDays(1), DateTime.MaxValue);
        }
Only a Problem in total overview.
The seperated projects assume, that the started duration is allready in the past.

Have to discuss, if this is still wanted, or if it should also predicted. Similar to the linegraph.

**Comment by DuplosFidibuss** [comment]
Fixed in #118
